### ISSUE TITLE
Font colors became much lighter?

### ISSUE THREAD

**Issue by nikackermann** [sindresorhus/hyper-snazzy#42] opened 2018-04-25 20:14 UTC
I've been using Hyper Terminal with the Hyper Snazzy for quite some time and today I opened it up and the colors became much lighter for some reason? Anyone know why this issue is happening? The colors used to be much brighter and vibrant.
<img width="860" alt="screen shot 2018-04-25 at 4 13 33 pm" src="https://user-images.githubusercontent.com/1296067/39270309-a4301cc0-48a3-11e8-985e-9993eedd2e65.png">

**Comment by georgewatts** [comment] 2018-04-25 22:43
Hi @nikackermann I think this might be a duplicate of issue #41, we have discussed some potential solutions for you there.

**Closed** 2018-05-20 18:14 UTC
