### ISSUE TITLE
add option for vibrancy

### ISSUE THREAD

**Issue by vdclouis** [sindresorhus/hyper-snazzy#14] opened 2016-12-16 14:12 UTC
Since version 1 you can now use the `vibrancy` option to achieve effects like:
![](https://cloud.githubusercontent.com/assets/4721750/21105323/f21f1240-c070-11e6-9c7a-e451288eac7c.png)

see [this](https://github.com/matheuss/hyper-simple-vibrancy) example and [this](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetvibrancytype-macos) for the different types.

**Comment by SamVerschueren** [comment] 2016-12-16 17:53
Duplicate of https://github.com/sindresorhus/hyper-snazzy/pull/7

**Closed by SamVerschueren** 2016-12-16 17:53 UTC
